# Generated by Django 4.2.5 on 2023-10-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_alumno_profesor_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('1', 'Programacion'), ('2', 'Marketing'), ('3', 'Producto'), ('4', 'Datos'), ('5', 'Ciberseguridad'), ('6', 'Finanzas')], max_length=20),
        ),
    ]
