# Generated by Django 4.2.5 on 2023-10-04 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_alter_curso_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='alumnos',
            new_name='alumno',
        ),
    ]
