# Generated by Django 4.2.5 on 2023-10-04 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_rename_alumnos_curso_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='alumno',
            new_name='alumnos',
        ),
    ]
