# Generated by Django 4.2.5 on 2023-10-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_rename_alumno_curso_alumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Teacher',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='profesor',
            new_name='teacher',
        ),
    ]
