# Generated by Django 4.2.5 on 2023-10-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_rename_alumno_student_rename_alumnos_curso_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.CharField(choices=[('1', 'Programming'), ('2', 'Marketing'), ('3', 'Product'), ('4', 'Data'), ('5', 'Cybersecurity'), ('6', 'Finance')], max_length=20),
        ),
    ]
